[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
dotenv = "0.15.0"
reqwest = "0.12.9"
tokio = { version = "1.42.0", features = ["full"] }
